### ISSUE TITLE
Package not importing

### ISSUE THREAD

**Issue by binghama** [rharkes/pyhaloxml#1]
Hi,

I was trying to import this package to convert HALO's ".annotation" files to geojson files using the "example2.py" script you provided. However, there was an error when executing line 2, `from pyhaloxml import HaloXML`

I received the following error:
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
Input In [10], in <cell line: 2>()
      1 from pathlib import Path
----> 2 from pyhaloxml import HaloXML
      4 pth = Path(Path.cwd(), "/EDC300D_czifiles/EDC300D_annotation_files", "2022_10_14__0652.annotations")
      5 pth

File /gpfs/gsfs8/users/annemb/conda/envs/snakemakePipeline/lib/python3.8/site-packages/pyhaloxml/__init__.py:1, in <module>
----> 1 from .HaloXML import HaloXML
      2 from .Region import Region
      3 from .Layer import Layer

File /gpfs/gsfs8/users/annemb/conda/envs/snakemakePipeline/lib/python3.8/site-packages/pyhaloxml/HaloXML.py:13, in <module>
     10 from lxml.etree import _ElementTree
     11 import geojson as gs
---> 13 from .Layer import Layer
     14 from .Region import Region
     15 from .inpoly import points_in_polygons

File /gpfs/gsfs8/users/annemb/conda/envs/snakemakePipeline/lib/python3.8/site-packages/pyhaloxml/Layer.py:9, in <module>
      7 from lxml.etree import _Attrib
      8 from shapely import geometry as sg
----> 9 from pyhaloxml.Region import Region
     10 from pyhaloxml.misc import Color
     13 class Layer:

File /gpfs/gsfs8/users/annemb/conda/envs/snakemakePipeline/lib/python3.8/site-packages/pyhaloxml/Region.py:10, in <module>
      8 from shapely import geometry as sg
      9 import geojson as gs
---> 10 from pyhaloxml.ellipse import ellipse2polygon
     11 from pyhaloxml.misc import RegionType, getvertices, closepolygon, getvertex
     14 class Region:

File /gpfs/gsfs8/users/annemb/conda/envs/snakemakePipeline/lib/python3.8/site-packages/pyhaloxml/ellipse.py:7, in <module>
      1 """
      2 Scripts to generate a polygon from an ellipse
      3 """
      4 import math
----> 7 def ellipse2polygon(a: float, b: float, n: int = 65) -> list[(float, float)]:
      8     """
      9     Generate n points at equal angles along an ellipse with major axis a and minor axis b
     10     :param a:
   (...)
     13     :return:
     14     """
     15     angles = [0]

TypeError: 'type' object is not subscriptable

Any idea what may be causing this?

**Comment by rharkes** [comment]
Hi @binghama ,

Thanks for your issue. Could you specify a few things:
* What version of pyhaloxml you are using? It might be that your on a version that does not properly support ellipses. I just uploaded version 2.4.1, could you try that one?
* Could you share your .annotation file somehow so that I can check what causes this error? It seems to fail here:
https://github.com/rharkes/pyhaloxml/blob/main/src/pyhaloxml/ellipse.py#L7
But I don't see how.

**Comment by binghama** [comment]
Hi @rharkes thanks for your prompt response! I just upgraded to 2.4.1, I was on 2.4.0 previously, but I am getting the same error. I've attached one of the .annotation files I'm working with.
[annotation_example.zip](https://github.com/rharkes/pyhaloxml/files/10490657/annotation_example.zip)

**Comment by rharkes** [comment]
Hi @binghama ,
Thanks for sharing the data. I tried to open your .annotations file and it does it without any error. 

Now that I read your error message more carefully it seems it already crashes at the import statement: `from pyhaloxml import HaloXML`. Because of this line `def ellipse2polygon(a: float, b: float, n: int = 65) -> list[(float, float)]:`. That would mean it has nothing to do with the file.

What python version are you using? I've loaded your file with Python 3.10.8

**Comment by rharkes** [comment]
I was able to replicate your error with python 3.8.3.

**Comment by binghama** [comment]
I am using python 3.8.

**Comment by rharkes** [comment]
Is it possible to upgrade to 3.9 or higher?

**Comment by rharkes** [comment]
I put python 3.9 or higher as required.

**Comment by binghama** [comment]
Thank you @rharkes !
