### ISSUE TITLE
pyhaloxml does not read all files

### ISSUE THREAD

**Issue by jonasteuwen** [rharkes/pyhaloxml#7]
The current version is not able to read the attached annotation file (provided by Rolf Harkes) 
[HaloMultilayerTest.txt](https://github.com/rharkes/pyhaloxml/files/13549600/HaloMultilayerTest.txt). Rename to .annotations

**Comment by rharkes** [comment]
It does read all files now. Thanks for the help and advise with improving this package. 

Sadly we cannot get all weird halo possibilities in the annotation files to convert to shapely or geojson. But "normal" annotation files will be converted without problems.

**Comment by jonasteuwen** [comment]
What are examples where it’s not possible?

**Comment by rharkes** [comment]
* Negative regions not in a positive region
* Negative pins

**Comment by jonasteuwen** [comment]
What is a negative polygon supposed to represent? Perhaps you can make a wrapper class with the polygon and a negative flag

**Comment by rharkes** [comment]
Exactly my question. I have no idea. The format allows for it, but it makes no sense from any point of view I can imagine. 

At the moment it just sends it as a region.

A use case could be someone accidentally annotating with negative regions (because they like dashed lines or something). The conversion now will work as expected, ignoring the negativity.
